### ISSUE TITLE
Be able to parse utf-16 text files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/xy-parser#5]
[181217_Cryo1-1_N1-2@25C.txt](https://github.com/cheminfo/xy-parser/files/4917221/181217_Cryo1-1_N1-2%4025C.txt)

**Comment by targos** [comment]
Web API: https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder

**Comment by lpatiny** [comment]
@targos Any idea how to guess the format of the file ? I received text files that may be utf8, utf16 of iso something.

**Comment by targos** [comment]
Unless the file has a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), I don't think that's possible

**Comment by lpatiny** [comment]
Great thanks. Didn't know about BOM but indeed this is the solution.
